/**
 * @author whenlove
 */

var world_statis_s_1 = [
    {"i": "CHINA","wc": "mil","e": "UNITED STATES","v": "4307"},
{"i": "CHINA","wc": "mil","e": "THAILAND","v": "26"},
{"i": "CHINA","wc": "mil","e": "KOREA REPUBLIC OF","v": "152"},
{"i": "CHINA","wc": "mil","e": "LUXEMBOURG","v": "6"},
{"i": "CHINA","wc": "mil","e": "CANADA","v": "167"},
{"i": "CHINA","wc": "mil","e": "MEXICO","v": "36"},
{"i": "CHINA","wc": "mil","e": "GERMANY","v": "1015"},
{"i": "CHINA","wc": "mil","e": "JAPAN","v": "103"},
{"i": "CHINA","wc": "mil","e": "SWEDEN","v": "139"},
{"i": "CHINA","wc": "mil","e": "BULGARIA","v": "11"},
{"i": "CHINA","wc": "mil","e": "UKRAINE","v": "93"},
{"i": "CHINA","wc": "mil","e": "FRANCE","v": "43"},
{"i": "CHINA","wc": "mil","e": "NETHERLANDS","v": "24"},
{"i": "CHINA","wc": "mil","e": "RUSSIAN FEDERATION","v": "174"},
{"i": "CHINA","wc": "mil","e": "SINGAPORE","v": "60"},
{"i": "CHINA","wc": "mil","e": "CZECH REPUBLIC","v": "38"},
{"i": "CHINA","wc": "mil","e": "UNITED KINGDOM","v": "47"},
{"i": "CHINA","wc": "mil","e": "COLOMBIA","v": "11"},
{"i": "CHINA","wc": "mil","e": "ITALY","v": "35"},
{"i": "CHINA","wc": "mil","e": "BRAZIL","v": "17"},
];

var world_statis_s_2 = [
    {"i": "CHINA","wc": "mil","e": "UNITED STATES","v": "2869"},
{"i": "CHINA","wc": "mil","e": "THAILAND","v": "109"},
{"i": "CHINA","wc": "mil","e": "KOREA REPUBLIC OF","v": "92"},
{"i": "CHINA","wc": "mil","e": "LUXEMBOURG","v": "3"},
{"i": "CHINA","wc": "mil","e": "CANADA","v": "108"},
{"i": "CHINA","wc": "mil","e": "MEXICO","v": "9"},
{"i": "CHINA","wc": "mil","e": "GERMANY","v": "341"},
{"i": "CHINA","wc": "mil","e": "JAPAN","v": "117"},
{"i": "CHINA","wc": "mil","e": "SWEDEN","v": "17"},
{"i": "CHINA","wc": "mil","e": "BULGARIA","v": "3"},
{"i": "CHINA","wc": "mil","e": "UKRAINE","v": "46"},
{"i": "CHINA","wc": "mil","e": "FRANCE","v": "25"},
{"i": "CHINA","wc": "mil","e": "NETHERLANDS","v": "10"},
{"i": "CHINA","wc": "mil","e": "RUSSIAN FEDERATION","v": "284"},
{"i": "CHINA","wc": "mil","e": "SINGAPORE","v": "17"},
{"i": "CHINA","wc": "mil","e": "CZECH REPUBLIC","v": "7"},
{"i": "CHINA","wc": "mil","e": "UNITED KINGDOM","v": "35"},
{"i": "CHINA","wc": "mil","e": "COLOMBIA","v": "5"},
{"i": "CHINA","wc": "mil","e": "INDIA","v": "410"},
{"i": "CHINA","wc": "mil","e": "BRAZIL","v": "13"},
];

var world_statis_s_3 = [
    {"i": "CHINA","wc": "mil","e": "UNITED STATES","v": "2422"},
{"i": "CHINA","wc": "mil","e": "THAILAND","v": "138"},
{"i": "CHINA","wc": "mil","e": "KOREA REPUBLIC OF","v": "102"},
{"i": "CHINA","wc": "mil","e": "LUXEMBOURG","v": "11"},
{"i": "CHINA","wc": "mil","e": "CANADA","v": "105"},
{"i": "CHINA","wc": "mil","e": "MEXICO","v": "37"},
{"i": "CHINA","wc": "mil","e": "GERMANY","v": "208"},
{"i": "CHINA","wc": "mil","e": "JAPAN","v": "117"},
{"i": "CHINA","wc": "mil","e": "SWEDEN","v": "22"},
{"i": "CHINA","wc": "mil","e": "BULGARIA","v": "33"},
{"i": "CHINA","wc": "mil","e": "UKRAINE","v": "185"},
{"i": "CHINA","wc": "mil","e": "FRANCE","v": "13"},
{"i": "CHINA","wc": "mil","e": "NETHERLANDS","v": "24"},
{"i": "CHINA","wc": "mil","e": "RUSSIAN FEDERATION","v": "205"},
{"i": "CHINA","wc": "mil","e": "SINGAPORE","v": "24"},
{"i": "CHINA","wc": "mil","e": "CZECH REPUBLIC","v": "13"},
{"i": "CHINA","wc": "mil","e": "UNITED KINGDOM","v": "27"},
{"i": "CHINA","wc": "mil","e": "COLOMBIA","v": "4"},
{"i": "CHINA","wc": "mil","e": "ITALY","v": "17"},
{"i": "CHINA","wc": "mil","e": "BRAZIL","v": "47"},
];

var world_statis_d_1 = [
    {"i": "CHINA","wc": "mil","e": "UNITED STATES","v": "19586"},
{"i": "CHINA","wc": "mil","e": "THAILAND","v": "2"},
{"i": "CHINA","wc": "mil","e": "KOREA REPUBLIC OF","v": "6966"},
{"i": "CHINA","wc": "mil","e": "LUXEMBOURG","v": "2886"},
{"i": "CHINA","wc": "mil","e": "CANADA","v": "153"},
{"i": "CHINA","wc": "mil","e": "MEXICO","v": "118"},
{"i": "CHINA","wc": "mil","e": "GERMANY","v": "308"},
{"i": "CHINA","wc": "mil","e": "JAPAN","v": "427"},
{"i": "CHINA","wc": "mil","e": "SWEDEN","v": "291"},
{"i": "CHINA","wc": "mil","e": "BULGARIA","v": "87"},
{"i": "CHINA","wc": "mil","e": "UKRAINE","v": "104"},
{"i": "CHINA","wc": "mil","e": "FRANCE","v": "69"},
{"i": "CHINA","wc": "mil","e": "NETHERLANDS","v": "266"},
{"i": "CHINA","wc": "mil","e": "RUSSIAN FEDERATION","v": "550"},
{"i": "CHINA","wc": "mil","e": "SINGAPORE","v": "21"},
{"i": "CHINA","wc": "mil","e": "CZECH REPUBLIC","v": "757"},
{"i": "CHINA","wc": "mil","e": "UNITED KINGDOM","v": "287"},
{"i": "CHINA","wc": "mil","e": "COLOMBIA","v": "133"},
{"i": "CHINA","wc": "mil","e": "ITALY","v": "87"},
{"i": "CHINA","wc": "mil","e": "BRAZIL","v": "16"},
];

var world_statis_d_2 = [
    {"i": "CHINA","wc": "mil","e": "UNITED STATES","v": "6725"},
{"i": "CHINA","wc": "mil","e": "THAILAND","v": "2120"},
{"i": "CHINA","wc": "mil","e": "KOREA REPUBLIC OF","v": "3751"},
{"i": "CHINA","wc": "mil","e": "LUXEMBOURG","v": "3405"},
{"i": "CHINA","wc": "mil","e": "CANADA","v": "312"},
{"i": "CHINA","wc": "mil","e": "MEXICO","v": "517"},
{"i": "CHINA","wc": "mil","e": "GERMANY","v": "870"},
{"i": "CHINA","wc": "mil","e": "JAPAN","v": "238"},
{"i": "CHINA","wc": "mil","e": "SWEDEN","v": "824"},
{"i": "CHINA","wc": "mil","e": "BULGARIA","v": "46"},
{"i": "CHINA","wc": "mil","e": "UKRAINE","v": "327"},
{"i": "CHINA","wc": "mil","e": "FRANCE","v": "87"},
{"i": "CHINA","wc": "mil","e": "NETHERLANDS","v": "1767"},
{"i": "CHINA","wc": "mil","e": "RUSSIAN FEDERATION","v": "188"},
{"i": "CHINA","wc": "mil","e": "SINGAPORE","v": "8"},
{"i": "CHINA","wc": "mil","e": "CZECH REPUBLIC","v": "6499"},
{"i": "CHINA","wc": "mil","e": "UNITED KINGDOM","v": "144"},
{"i": "CHINA","wc": "mil","e": "COLOMBIA","v": "256"},
{"i": "CHINA","wc": "mil","e": "ITALY","v": "43"},
{"i": "CHINA","wc": "mil","e": "BRAZIL","v": "14"},
];

var world_statis_d_3 = [
    {"i": "CHINA","wc": "mil","e": "美国","v": "6951"},
{"i": "CHINA","wc": "mil","e": "泰国","v": "4291"},
{"i": "CHINA","wc": "mil","e": "韩国","v": "1629"},
{"i": "CHINA","wc": "mil","e": "卢森堡","v": "1557"},
{"i": "CHINA","wc": "mil","e": "加拿大","v": "463"},
{"i": "CHINA","wc": "mil","e": "墨西哥","v": "390"},
{"i": "CHINA","wc": "mil","e": "德国","v": "299"},
{"i": "CHINA","wc": "mil","e": "日本","v": "273"},
{"i": "CHINA","wc": "mil","e": "瑞典","v": "263"},
{"i": "CHINA","wc": "mil","e": "保加利亚","v": "189"},
{"i": "CHINA","wc": "mil","e": "乌克兰","v": "178"},
{"i": "CHINA","wc": "mil","e": "法国","v": "109"},
{"i": "CHINA","wc": "mil","e": "荷兰","v": "99"},
{"i": "CHINA","wc": "mil","e": "俄罗斯","v": "68"},
{"i": "CHINA","wc": "mil","e": "新加坡","v": "60"},
{"i": "CHINA","wc": "mil","e": "捷克","v": "57"},
{"i": "CHINA","wc": "mil","e": "英国","v": "43"},
{"i": "CHINA","wc": "mil","e": "哥伦比亚","v": "41"},
{"i": "CHINA","wc": "mil","e": "意大利","v": "37"},
{"i": "CHINA","wc": "mil","e": "巴西","v": "30"},
];